version: 1
updated_at_utc: "2026-02-21T00:00:00Z"

# Logical identities used for repository automation policy.
# Note: these are policy identities; GitHub account provisioning must be done outside this repo.
users:
  - id: jarvis4.0
    role: operator
    agent_file: .github/agents/jarvis4.0.agent.md
    target: github-copilot
    github_login: null
    org: vNodes-Co
  - id: jarvis4.0_vscode
    role: operator
    agent_file: .github/agents/jarvis4.0_vscode.agent.md
    target: vscode
    github_login: null
    org: vNodes-Co
  - id: jarvisBoss
    role: reviewer-approver
    agent_file: .github/agents/reviewer.agent.md
    github_login: jarvisBoss
    org: vNodes-Co

policy:
  pull_request:
    required_reviewer_ids:
      - jarvisBoss