package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// bashCompletionScript is the static bash completion script for vprox.
// Generated by `vprox completion bash`.
const bashCompletionScript = `# vprox bash completion script
# Generated by: vprox completion bash
#
# To enable in the current shell session:
#   source <(vprox completion bash)
#
# To install permanently:
#   vprox completion --install-bash
#   # Then add to ~/.bashrc: source ~/.bash_completion.d/vprox

_vprox_completions() {
    local cur prev words cword
    _init_completion 2>/dev/null || {
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    }

    local commands="start stop restart status fleet mod chain config completion vops"
    local global_flags="--help --version --home --config --validate --info --dry-run --quiet --verbose --daemon --debug --with-vops -d"

    if [[ $cword -eq 1 ]]; then
        COMPREPLY=($(compgen -W "${commands} ${global_flags}" -- "$cur"))
        return 0
    fi

    local subcmd="${words[1]}"
    case "$subcmd" in
        config)
            COMPREPLY=($(compgen -W "ports settings chain vlog fleet infra backup list validate" -- "$cur"))
            ;;
        fleet)
            COMPREPLY=($(compgen -W "list status push sync chains unregister" -- "$cur"))
            ;;
        completion)
            COMPREPLY=($(compgen -W "bash zsh fish --install-bash --install-zsh" -- "$cur"))
            ;;
        vops)
            COMPREPLY=($(compgen -W "start stop status version archives accounts threats enrich cache ingest" -- "$cur"))
            ;;
        start|stop|restart|status)
            COMPREPLY=($(compgen -W "${global_flags}" -- "$cur"))
            ;;
        *)
            COMPREPLY=($(compgen -W "${global_flags}" -- "$cur"))
            ;;
    esac

    return 0
}

complete -F _vprox_completions vprox
`

// zshCompletionScript is the static zsh completion script for vprox.
// Generated by `vprox completion zsh`.
const zshCompletionScript = `#compdef vprox
# vprox zsh completion script
# Generated by: vprox completion zsh
#
# To enable in the current shell session:
#   source <(vprox completion zsh)
#
# To install permanently:
#   vprox completion --install-zsh

_vprox() {
    local -a commands
    commands=(
        'start:start the vProx proxy server (foreground, journald-friendly)'
        'stop:stop the vProx.service daemon'
        'restart:restart the vProx.service daemon'
        'status:show service status'
        'fleet:manage remote VMs and deployments'
        'mod:manage vProx ecosystem modules'
        'chain:chain node status and upgrade tracking'
        'config:interactive TOML configuration wizard'
        'completion:generate shell completion scripts'
        'vops:vOps dashboard and analytics (integrated vLog)'
    )

    local -a global_flags
    global_flags=(
        '--help:show help and exit'
        '--version:show version and exit'
        '--home:override VPROX_HOME directory'
        '--config:override config directory'
        '--validate:validate configs and exit'
        '--info:show loaded config summary and exit'
        '--dry-run:load everything but do not start server'
        '--quiet:suppress non-error output'
        '--verbose:verbose logging output'
        '--daemon:start as background daemon via sudo service'
        '--debug:enable debug mode'
        '--with-vops:start with vOps/dashboard module'
        '-d:alias for --daemon'
    )

    _arguments -C \
        '1: :->command' \
        '*:: :->args'

    case $state in
        command)
            _describe 'vprox command' commands
            _describe 'global flag' global_flags
            ;;
        args)
            case $words[1] in
                config)
                    _values 'config subcommand' \
                        'ports[configure port assignments]' \
                        'settings[general proxy settings]' \
                        'chain[chain proxy config]' \
                        'vlog[vLog/vOps config]' \
                        'fleet[fleet SSH settings]' \
                        'infra[infra datacenter registry]' \
                        'backup[backup automation settings]' \
                        'list[list all loaded configs]' \
                        'validate[validate all config files]'
                    ;;
                fleet)
                    _values 'fleet subcommand' \
                        'list[list registered VMs]' \
                        'status[show fleet status]' \
                        'push[push scripts to fleet]' \
                        'sync[sync fleet state]' \
                        'chains[list registered chains]' \
                        'unregister[unregister a chain from SQLite]'
                    ;;
                completion)
                    _values 'shell' 'bash' 'zsh' 'fish'
                    _arguments \
                        '--install-bash[install bash completion to ~/.bash_completion.d/vprox]' \
                        '--install-zsh[install zsh completion]'
                    ;;
                vops)
                    _values 'vops subcommand' \
                        'start[start vOps standalone]' \
                        'stop[stop vOps]' \
                        'status[show vOps status]' \
                        'version[show vOps version]' \
                        'archives[list log archives]' \
                        'accounts[manage IP accounts]' \
                        'threats[view threat intelligence]' \
                        'enrich[enrich IP addresses]' \
                        'cache[cache management]' \
                        'ingest[ingest log archives]'
                    ;;
                *)
                    _describe 'global flag' global_flags
                    ;;
            esac
            ;;
    esac
}

_vprox "$@"
`

// fishCompletionScript is the static fish completion script for vprox.
// Generated by `vprox completion fish`.
const fishCompletionScript = `# vprox fish completion script
# Generated by: vprox completion fish
#
# To install:
#   vprox completion fish > ~/.config/fish/completions/vprox.fish
# Or:
#   vprox completion --install-fish  (not yet available; use manual install above)

# Disable file completion by default
complete -c vprox -f

# ---- Top-level commands ----
complete -c vprox -n '__fish_use_subcommand' -a 'start'      -d 'Start vProx proxy server (foreground)'
complete -c vprox -n '__fish_use_subcommand' -a 'stop'       -d 'Stop vProx service'
complete -c vprox -n '__fish_use_subcommand' -a 'restart'    -d 'Restart vProx service'
complete -c vprox -n '__fish_use_subcommand' -a 'status'     -d 'Show service status'
complete -c vprox -n '__fish_use_subcommand' -a 'fleet'      -d 'Manage remote VMs and deployments'
complete -c vprox -n '__fish_use_subcommand' -a 'mod'        -d 'Manage vProx modules'
complete -c vprox -n '__fish_use_subcommand' -a 'chain'      -d 'Chain node status and upgrade tracking'
complete -c vprox -n '__fish_use_subcommand' -a 'config'     -d 'Interactive TOML configuration wizard'
complete -c vprox -n '__fish_use_subcommand' -a 'completion' -d 'Generate shell completion scripts'
complete -c vprox -n '__fish_use_subcommand' -a 'vops'       -d 'vOps dashboard and analytics'

# ---- Global flags ----
complete -c vprox -l help        -d 'Show help and exit'
complete -c vprox -l version     -d 'Show version and exit'
complete -c vprox -l home        -r -d 'Override VPROX_HOME directory'
complete -c vprox -l config      -r -d 'Override config directory'
complete -c vprox -l validate    -d 'Validate configs and exit'
complete -c vprox -l info        -d 'Show loaded config summary and exit'
complete -c vprox -l dry-run     -d 'Load everything but do not start server'
complete -c vprox -l quiet       -d 'Suppress non-error output'
complete -c vprox -l verbose     -d 'Verbose logging output'
complete -c vprox -l daemon      -d 'Start as background daemon'
complete -c vprox -l debug       -d 'Enable debug mode'
complete -c vprox -l with-vops   -d 'Start with vOps/dashboard module'
complete -c vprox -s d           -d 'Alias for --daemon'

# ---- config subcommands ----
complete -c vprox -n '__fish_seen_subcommand_from config' -a 'ports'    -d 'Configure port assignments'
complete -c vprox -n '__fish_seen_subcommand_from config' -a 'settings' -d 'General proxy settings'
complete -c vprox -n '__fish_seen_subcommand_from config' -a 'chain'    -d 'Chain proxy config'
complete -c vprox -n '__fish_seen_subcommand_from config' -a 'vlog'     -d 'vLog/vOps config'
complete -c vprox -n '__fish_seen_subcommand_from config' -a 'fleet'    -d 'Fleet SSH settings'
complete -c vprox -n '__fish_seen_subcommand_from config' -a 'infra'    -d 'Infra datacenter registry'
complete -c vprox -n '__fish_seen_subcommand_from config' -a 'backup'   -d 'Backup automation settings'
complete -c vprox -n '__fish_seen_subcommand_from config' -a 'list'     -d 'List all loaded configs'
complete -c vprox -n '__fish_seen_subcommand_from config' -a 'validate' -d 'Validate all config files'

# ---- fleet subcommands ----
complete -c vprox -n '__fish_seen_subcommand_from fleet' -a 'list'       -d 'List registered VMs'
complete -c vprox -n '__fish_seen_subcommand_from fleet' -a 'status'     -d 'Show fleet status'
complete -c vprox -n '__fish_seen_subcommand_from fleet' -a 'push'       -d 'Push scripts to fleet'
complete -c vprox -n '__fish_seen_subcommand_from fleet' -a 'sync'       -d 'Sync fleet state'
complete -c vprox -n '__fish_seen_subcommand_from fleet' -a 'chains'     -d 'List registered chains'
complete -c vprox -n '__fish_seen_subcommand_from fleet' -a 'unregister' -d 'Unregister a chain'

# ---- completion subcommands ----
complete -c vprox -n '__fish_seen_subcommand_from completion' -a 'bash'  -d 'Generate bash completion script'
complete -c vprox -n '__fish_seen_subcommand_from completion' -a 'zsh'   -d 'Generate zsh completion script'
complete -c vprox -n '__fish_seen_subcommand_from completion' -a 'fish'  -d 'Generate fish completion script'
complete -c vprox -n '__fish_seen_subcommand_from completion' -l 'install-bash' -d 'Install bash completion to ~/.bash_completion.d/vprox'
complete -c vprox -n '__fish_seen_subcommand_from completion' -l 'install-zsh'  -d 'Install zsh completion'

# ---- vops subcommands ----
complete -c vprox -n '__fish_seen_subcommand_from vops' -a 'start'    -d 'Start vOps standalone'
complete -c vprox -n '__fish_seen_subcommand_from vops' -a 'stop'     -d 'Stop vOps'
complete -c vprox -n '__fish_seen_subcommand_from vops' -a 'status'   -d 'Show vOps status'
complete -c vprox -n '__fish_seen_subcommand_from vops' -a 'version'  -d 'Show vOps version'
complete -c vprox -n '__fish_seen_subcommand_from vops' -a 'archives' -d 'List log archives'
complete -c vprox -n '__fish_seen_subcommand_from vops' -a 'accounts' -d 'Manage IP accounts'
complete -c vprox -n '__fish_seen_subcommand_from vops' -a 'threats'  -d 'View threat intelligence'
complete -c vprox -n '__fish_seen_subcommand_from vops' -a 'enrich'   -d 'Enrich IP addresses'
complete -c vprox -n '__fish_seen_subcommand_from vops' -a 'cache'    -d 'Cache management'
complete -c vprox -n '__fish_seen_subcommand_from vops' -a 'ingest'   -d 'Ingest log archives'
`

// generateBashCompletion returns the static bash completion script for vprox.
func generateBashCompletion() string {
	return bashCompletionScript
}

// generateZshCompletion returns the static zsh _vprox completion function for vprox.
func generateZshCompletion() string {
	return zshCompletionScript
}

// generateFishCompletion returns the static fish completion script for vprox.
func generateFishCompletion() string {
	return fishCompletionScript
}

// installCompletion writes the completion script for the specified shell to its
// conventional per-user completion directory and prints setup instructions.
//
// Supported shells: bash, zsh.
func installCompletion(shell, script string) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("installCompletion: get home dir: %w", err)
	}

	var dest, instructions string

	switch shell {
	case "bash":
		dir := filepath.Join(homeDir, ".bash_completion.d")
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("installCompletion: mkdir %s: %w", dir, err)
		}
		dest = filepath.Join(dir, "vprox")
		instructions = fmt.Sprintf(
			"Add the following line to ~/.bashrc to load completions:\n"+
				"  source %s\n\n"+
				"Or reload in the current session:\n"+
				"  source <(vprox completion bash)",
			dest,
		)

	case "zsh":
		// Probe in order: oh-my-zsh, ~/.zsh/completions, ~/.zshrc.d
		dir := ""
		candidates := []string{
			filepath.Join(homeDir, ".oh-my-zsh", "completions"),
			filepath.Join(homeDir, ".zsh", "completions"),
			filepath.Join(homeDir, ".zshrc.d"),
		}
		for _, c := range candidates {
			if _, statErr := os.Stat(c); statErr == nil {
				dir = c
				break
			}
		}
		if dir == "" {
			// Create ~/.zsh/completions as fallback
			dir = filepath.Join(homeDir, ".zsh", "completions")
			if err := os.MkdirAll(dir, 0755); err != nil {
				return fmt.Errorf("installCompletion: mkdir %s: %w", dir, err)
			}
		}
		dest = filepath.Join(dir, "_vprox")
		instructions = fmt.Sprintf(
			"Ensure %s is in $fpath. Add to ~/.zshrc if needed:\n"+
				"  fpath=(%s $fpath)\n"+
				"  autoload -U compinit && compinit",
			dir, dir,
		)

	default:
		return fmt.Errorf("unsupported shell %q for --install (supported: bash, zsh)", shell)
	}

	if err := os.WriteFile(dest, []byte(script), 0644); err != nil {
		return fmt.Errorf("installCompletion: write %s: %w", dest, err)
	}

	fmt.Printf("✓ Installed %s completion → %s\n\n", shell, dest)
	fmt.Println(instructions)
	return nil
}

// runCompletionCmd handles the `vprox completion` command.
//
// Usage:
//
//	vprox completion bash            — print bash completion script to stdout
//	vprox completion zsh             — print zsh completion script to stdout
//	vprox completion fish            — print fish completion script to stdout
//	vprox completion --install-bash  — install bash completion file
//	vprox completion --install-zsh   — install zsh completion file
func runCompletionCmd(args []string) {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "Usage: vprox completion [bash|zsh|fish]")
		fmt.Fprintln(os.Stderr, "       vprox completion --install-bash")
		fmt.Fprintln(os.Stderr, "       vprox completion --install-zsh")
		os.Exit(1)
	}

	// Scan for install flags (may appear before or instead of shell name)
	for _, a := range args {
		switch a {
		case "--install-bash":
			if err := installCompletion("bash", generateBashCompletion()); err != nil {
				fmt.Fprintf(os.Stderr, "vprox: %v\n", err)
				os.Exit(1)
			}
			return
		case "--install-zsh":
			if err := installCompletion("zsh", generateZshCompletion()); err != nil {
				fmt.Fprintf(os.Stderr, "vprox: %v\n", err)
				os.Exit(1)
			}
			return
		}
	}

	shell := strings.ToLower(args[0])
	switch shell {
	case "bash":
		fmt.Print(generateBashCompletion())
	case "zsh":
		fmt.Print(generateZshCompletion())
	case "fish":
		fmt.Print(generateFishCompletion())
	default:
		fmt.Fprintf(os.Stderr, "vprox completion: unknown shell %q\n", shell)
		fmt.Fprintln(os.Stderr, "Supported shells: bash, zsh, fish")
		os.Exit(1)
	}
}
